type: transformer
train-sets:
  - /d/Job_Requirements/PracticalProjectsFromDrYe/AIE-F/assignment-submission/class-22/TheinGiKyaw_Assignment7/g2p-par/train.ph
  - /d/Job_Requirements/PracticalProjectsFromDrYe/AIE-F/assignment-submission/class-22/TheinGiKyaw_Assignment7/g2p-par/train.my
valid-sets:
  - /d/Job_Requirements/PracticalProjectsFromDrYe/AIE-F/assignment-submission/class-22/TheinGiKyaw_Assignment7/g2p-par/dev.ph
  - /d/Job_Requirements/PracticalProjectsFromDrYe/AIE-F/assignment-submission/class-22/TheinGiKyaw_Assignment7/g2p-par/dev.my
vocabs:
  - /d/Job_Requirements/PracticalProjectsFromDrYe/AIE-F/assignment-submission/class-22/TheinGiKyaw_Assignment7/g2p-par/vocab/vocab.shared.yml
  - /d/Job_Requirements/PracticalProjectsFromDrYe/AIE-F/assignment-submission/class-22/TheinGiKyaw_Assignment7/g2p-par/vocab/vocab.shared.yml
model: /d/Job_Requirements/PracticalProjectsFromDrYe/AIE-F/assignment-submission/class-22/TheinGiKyaw_Assignment7/model.transformer.baseline_like.phmy/model.npz
max-length: 100
mini-batch-fit: true
workspace: 3000
maxi-batch: 100
transformer-heads: 8
transformer-dropout: 0.3
transformer-dim-ffn: 2048
transformer-ffn-activation: swish
transformer-postprocess-emb: d
transformer-postprocess: dan
enc-depth: 2
dec-depth: 2
tied-embeddings-all: true
learn-rate: 0.0003
lr-decay-inv-sqrt: 16000
lr-warmup: 0
lr-report: true
label-smoothing: 0.1
clip-norm: 5
valid-freq: 5000
save-freq: 5000
disp-freq: 500
valid-metrics:
  - cross-entropy
  - perplexity
  - bleu
early-stopping: 10
beam-size: 6
normalize: 0.6
log: /d/Job_Requirements/PracticalProjectsFromDrYe/AIE-F/assignment-submission/class-22/TheinGiKyaw_Assignment7/model.transformer.baseline_like.phmy/train.log
valid-log: /d/Job_Requirements/PracticalProjectsFromDrYe/AIE-F/assignment-submission/class-22/TheinGiKyaw_Assignment7/model.transformer.baseline_like.phmy/valid.log
valid-translation-output: /d/Job_Requirements/PracticalProjectsFromDrYe/AIE-F/assignment-submission/class-22/TheinGiKyaw_Assignment7/model.transformer.baseline_like.phmy/valid.ph-my.output
overwrite: true
keep-best: true
seed: 1111
devices:
  - 0
cpu-threads: 0
quiet-translation: true
